# Generated by Django 4.2.6 on 2023-10-22 11:49

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=75, unique=True, validators=[users.models.isusername])),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=13, validators=[users.models.isphone])),
                ('address', models.CharField(max_length=150)),
            ],
        ),
    ]
